# Generated by Django 5.0 on 2024-01-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_userprofile_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='university_name',
            field=models.TextField(null=True),
        ),
    ]
