# Generated by Django 4.2.7 on 2024-01-18 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_userprofile_university_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.TextField()),
                ('course_name', models.TextField()),
                ('completed_modules', models.JSONField(null=True)),
                ('transfer_credits_requests', models.JSONField(null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.userprofile', to_field='email')),
            ],
        ),
    ]
