# Generated by Django 4.2.7 on 2024-01-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('full_name', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('university_name', models.TextField(null=True)),
                ('signup_using', models.TextField()),
                ('role', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.TextField()),
                ('course_name', models.TextField()),
                ('completed_modules', models.JSONField(null=True)),
                ('transfer_credits_requests', models.JSONField(null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', to_field='email')),
            ],
        ),
    ]
